@isTest
public with sharing class LocaleFormattedDatetimeContrlTest {
	// public static User CreateSObject() {
	// 		BatchSettings__c testBatch = (BatchSettings__c)TestDataTemplates.createSObject(new BatchSettings__c(), true);
	// 		App_Settings__c testApp = (App_Settings__c)TestDataTemplates.createSObject(new App_Settings__c(), true);
	// 		User testUser = (User)TestDataTemplates.createSObject(new User(
	// 			Username = 'testerson@causeview.com',
	// 			LastName = 'testerson',
	// 		  Email = 'Test@email.com',
	// 			Alias = 'Tester',
	// 			CommunityNickname = 'Tester',
	// 			TimeZoneSidKey = 'America/New_York',
	// 			LocaleSidKey = 'en_CA',
	// 		  EmailEncodingKey = 'ISO-8859-1',
	// 			ProfileId = '00e46000001QmOgAAK',
	// 			LanguageLocaleKey = 'en_US'), true);

	// 		return testUser;
	// }

	// @isTest static void TestGetTimeZoneValue() {
	// 	User expectedUser = CreateSObject();

	// 	Test.startTest();
	// 		LocaleFormattedDatetimeContrl localeFDTC = new LocaleFormattedDatetimeContrl();
	// 		String timeZoneValue = localeFDTC.getTimeZoneValue();
	// 	Test.stopTest();
	// }
}